# Generated by Django 5.2.3 on 2025-08-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='customuser',
        ),
    ]
