# Generated by Django 5.2.3 on 2025-08-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_consultants_duration_consultants_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultants',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
