# Generated by Django 5.2.3 on 2025-08-21 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_consultants_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultants',
            name='duration',
        ),
    ]
